// Emits src/schema.gen.ts from the pinned OpenAPI spec.
//
// The output SCHEMAS are what MCP clients validate a tool result against, so
// deriving them from the spec is what keeps a tool's advertised shape and the
// shape the API actually serves from being two separate claims. A column added
// to the catalog reaches the manifest by re-pinning the spec, not by anyone
// remembering to widen a hand-written schema here.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const spec = JSON.parse(readFileSync(resolve(root, 'spec/openapi.json'), 'utf8'));

const schema = (name) => {
    const node = spec.components.schemas[name];
    if (node === undefined) {
        throw new Error(`spec has no components.schemas.${name}`);
    }
    return deref(spec, node);
};

const out = `${banner()}

export const SPEC_VERSION = '${spec.info.version}';

/** The most history rows \`list_downloads\` may ask for. The API clamps to the same. */
export const DOWNLOADS_LIMIT = ${queryParamMax('/api/v2/database/downloads', 'limit')};

// Matches the shape the MCP Tool type wants for inputSchema/outputSchema, so a
// generated schema can be handed straight to a tool definition.
export interface ObjectSchema {
    type: 'object';
    properties?: Record<string, object>;
    required?: string[];
    [k: string]: unknown;
}

export const DATABASE_SCHEMA: ObjectSchema = ${ts(schema('Database'))};

export const DATABASE_METADATA_SCHEMA: ObjectSchema = ${ts(schema('DatabaseMetadata'))};

export const DB_CHECKSUMS_SCHEMA: ObjectSchema = ${ts(schema('DbChecksums'))};

export const DOWNLOAD_SCHEMA: ObjectSchema = ${ts(schema('Download'))};
`;

writeFileSync(resolve(root, 'src/schema.gen.ts'), out);
console.log(`src/schema.gen.ts  (spec ${spec.info.version})`);

// A numeric bound the API enforces, read off the spec rather than restated in
// the manifest. The cap reaches a tool description and its runtime check by
// re-pinning the spec, which is the same contract the output schemas have; a
// hand-written copy is free to keep advertising 200 after the API moves.
function queryParamMax(path, name) {
    const params = spec.paths[path]?.get?.parameters ?? [];
    const param = params.find((q) => q.name === name && q.in === 'query');
    const max = param?.schema?.maximum;
    if (typeof max !== 'number') {
        throw new Error(`spec has no numeric maximum for GET ${path} ?${name}`);
    }
    return max;
}

// Inlines every $ref. MCP clients validate tool output with an ordinary JSON
// Schema validator that has no document to resolve a local $ref against, so a
// schema carrying one would fail validation rather than skip it.
function deref(doc, node, seen = new Set()) {
    if (node === null || typeof node !== 'object') {
        return node;
    }
    if (Array.isArray(node)) {
        return node.map((n) => deref(doc, n, seen));
    }
    if (typeof node.$ref === 'string') {
        if (seen.has(node.$ref)) {
            throw new Error(`circular $ref: ${node.$ref}`);
        }
        const path = node.$ref.replace(/^#\//, '').split('/');
        let target = doc;
        for (const p of path) {
            target = target[p];
        }
        if (target === undefined) {
            throw new Error(`unresolvable $ref: ${node.$ref}`);
        }
        return deref(doc, target, new Set([...seen, node.$ref]));
    }
    const out = {};
    for (const [k, v] of Object.entries(node)) {
        if (k === 'example' || k === 'examples') {
            continue;
        }
        out[k] = deref(doc, v, seen);
    }
    return out;
}

function ts(node) {
    return JSON.stringify(node, null, 4);
}

function banner() {
    return '// Code generated by scripts/gen-schema.mjs from spec/openapi.json. DO NOT EDIT.';
}
